//auth action types
export const START_AUTH = "START_AUTH";
export const SUCCESS_AUTH = "SUCCESS";
export const SUCCESS_UPLOAD = "SUCCESS_UPLOAD";
export const FAIL_AUTH = "FAIL_AUTH";
export const LOGOUT_AUTH = "LOGOUT_AUTH";
export const SET_LOGGED_USER = "SET_LOGGED_USER";
export const SET_LOGGED_USER_REQUEST = "SET_LOGGED_USER_REQUEST";
export const SET_LOGGED_USER_SUCCESS = "SET_LOGGED_USER_SUCCESS";
export const SET_LOGGED_OUT_USER = "SET_LOGGED_OUT_USER";

//user action types
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const UPDATE_CURRENT_USER_SUCCESS = "UPDATE_CURRENT_USER_SUCCESS";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";

//comment acction types
export const GET_COMMENTS = "GET_COMMENTS";
export const GET_COMMENT = "GET_COMMENT";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

//Search action Types
export const GET_USERS = "GET_USERS";
export const FAIL_GET_USERS = "FAIL_GET_USERS";
export const GET_SEARCHED_USER = "GET_SEARCHED_USER";
export const SET_SEARCHED_USER = "SET_SEARCHED_USER";
export const FILTER_USERS = "FILTER_USERS";
export const LOADING_USERS = "LOADING_USERS";

//movie action types
export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAIL = "GET_MOVIE_FAIL";
export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";
export const ADD_LIKE_MOVIE = "ADD_LIKE_MOVIE";
export const REMOVE_LIKE_MOVIE = "REMOVE_LIKE_MOVIE";
export const ADD_WATCH_MOVIE = "ADD_WATCH_MOVIE";
export const REMOVE_WATCH_MOVIE = "REMOVE_WATCH_MOVIE";
export const ADD_LIKE_SELECTED_MOVIE = "ADD_LIKE_SELECTED_MOVIE";
export const REMOVE_LIKE_SELECTED_MOVIE = "REMOVE_LIKE_SELECTED_MOVIE";
export const ADD_WATCH_SELECTED_MOVIE = "ADD_WATCH_SELECTED_MOVIE";
export const REMOVE_WATCH_SELECTED_MOVIE = "REMOVE_WATCH_SELECTED_MOVIE";
